### ISSUE TITLE
Drum channels with custom names do not show correctly in mod channels.

### ISSUE THREAD

**Issue by carsonetb** [MainCharacteroftheProblem/ultrabox#2]
If you've named your channels with custom names (including drum channels) and then add a mod channel for drums, you can see that the name on the side is the name of the first instrument channel (and if you have a channel for the second drum, the name on the side is the name of the second instrument channel). Here is a screenshot of what this looks like (apologies for the super dark theme): 
![image](https://github.com/MainCharacteroftheProblem/ultrabox/assets/63245844/326a9935-c667-4419-9aaa-da52024d4b1a)
You should be able to easily recreate this by following the steps above or going to this test I made in UltraBox: 

[https://maincharacteroftheproblem.github.io/ultrabox/#g4N08Untitledn231s0k0l00e03t1Ua7g0fj07r4O_U0fTest%20Name%2010fTest%20Name%2020fTest%20Name%2030fTest%20Name%2040fTest%20Name%2050dMod%20Channeli0o32T0v0pu41f0000qg410Oad040w1h0E0T0v0pu1ef0000q040Oad040xQh0E0T4v0pui0f1a0q050Oa1z8888onapap4oSBKSJJAArriiiiii07JCABrzrrrrrrr00YrkqHrsrrrrjr005zrAqzrjzrrqr1jRjrqGGrrzsrsA099ijrABJJJIAzrrtirqrqjqixzsrAjrqjiqaqqysttAJqjikikrizrHtBJJAzArzrIsRCITKSS099ijrAJS____Qg99habbCAYrDzh00E0T3v0pui9f0000qwB16110Oa0d080SW86bmhkrrzrkrrrE1b8T3v0pul0f1a0qw52c10Oa0d030S_____XrrrrrrrrrE0T9v0pu00f0000q00d040E0b4h400000000h4g000000014h0000000000000000000000000000000000000000p1a0000003_Y0](url)

**Comment by MainCharacteroftheProblem** [comment]
Ok, so this is apparently not just an issue with UltraBox, but with Jummbox too. I'm going to dm Jummbus this and hopefully they'll fix the issue

**Comment by carsonetb** [comment]
Okay, cool!
