### ISSUE TITLE
how do I get the old sampled audios back in or revert the program?

### ISSUE THREAD

**Issue by SapphicMayDay** [MainCharacteroftheProblem/ultrabox#4]
After update 2.0.2 I cant find any of the sampled presets and it broke a bunch of my work. Is there a way to go back a version or way of getting the sound files for the sampled interments so I can reinsert them into ultraabox again?

**Comment by MainCharacteroftheProblem** [comment]
Go to the "Edit" menu, scroll down to the very bottom, and click on "Add Custom Samples...". On the custom sample prompt, type in "legacysamples" and hit enter.

**Comment by MainCharacteroftheProblem** [comment]
A better ui is coming in the next update

**Comment by MainCharacteroftheProblem** [comment]
Oh, and json is probably broken, that's getting fixed in the next update as well
